### ISSUE TITLE
Middleware breaks dispatching

### ISSUE THREAD

**Issue by vocksel** [roblox-ts/rbx-rodux#4]
Calls to `dispatch` compile to dot notation when using middleware, which prevents actions from ever dispatching.

```typescript
const sharedStore = new Store(rootReducer, undefined, [
    loggerMiddleware
])

sharedStore.dispatch({ type: "FOO", payload: "bar" })
```

```lua
local sharedStore = Store.new(rootReducer, nil, { loggerMiddleware });
sharedStore.dispatch({ -- note . instead of :
	type = "FOO";
	payload = "bar";
});
```

Without middleware (normal):

```typescript
const sharedStore = new Store(rootReducer)

sharedStore.dispatch({ type: "FOO", payload: "bar" })
```

```lua
local sharedStore = Store.new(rootReducer);
sharedStore:dispatch({ -- works fine and actions dispatch normally
	type = "FOO";
	payload = "bar";
});
```

The reason they don't dispatch is because of this in `Store.new()`:

![code_2019-02-10_23-10-49](https://user-images.githubusercontent.com/3081936/52545983-cf1c0400-2d89-11e9-9368-3399ffe5b490.png)

The action turns into `self`, instead of being part of the vararg.

**Comment by Vorlias** [comment]
Let me know if this is still an issue with `0.0.11`.
